### ISSUE TITLE
diff between minnan and mandarin

### ISSUE THREAD

**Issue by yt605155624** [GitYCC/g2pW#9]
头发
- minnan: 头发（fa3）
- mandarin: 头发（fa4）

拥抱
- minnan: 拥（yong3）抱
- mandarin: 拥（yong1）抱

.. maybe there are many cases..

Although this tool can handle polyphony words well, it is wrong for some common Mandarin pronunciation, maybe for mandarin users, we can use pypinyin to get `partial_results` in prepare_data ?

we can first replace the non polyphone chars:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/24568452/184079166-5c9a9028-4939-41f5-a642-be00c3a5d224.png">

but "拥" is polyphone, I need to find another way to solve it

```text
擁 ㄩㄥ3
擁 ㄩㄥ1
```
maybe we have to modify `POLYPHONIC_CHARS.txt` refer to this https://www.zhihu.com/question/31151037

**Comment by GitYCC** [comment]
Yes, there has some difference between Taiwan Mandarin and Chinese Mandarin.
So, in order to use g2p in Taiwan, we collect and annotate the training data for the situation. Hence, this model is trained that dataset.

Some suggests for you to handle this problem:
1. For monophonic characters, you can revise the dictionary
2. Train g2pW on high qaulity Chinese Mandarin dataset (maybe?

**Comment by jinfagang** [comment]
@GitYCC  Does there any plan to traing a Chinese Mandarin version as well?
